### ISSUE TITLE
Error processing PDFs

### ISSUE THREAD

**Issue by SamBamBam** [junruxiong/IncarnaMind#3]
After adding my PDFs one by one to the /data folder, there is one file that throws the error

```
Traceback (most recent call last):
  File "[...]/IncarnaMind/docs2db.py", line 182, in process_metadata
    file_name_with_extension = os.path.basename(doc[0].metadata["source"])
IndexError: list index out of range
```
Adding `for d in doc: print("metadata:", d.metadata)` prints no metadata at all for that doc, I'm not sure why.

Removing the problematic PDF, the files all process but then I get the error

```
Traceback (most recent call last):
  File "[...]/IncarnaMind/docs2db.py", line 347, in <module>
    process_files()
  File "[...]/IncarnaMind/docs2db.py", line 337, in process_files
    file_names2pickle(file_names, save_name="file_names")
  File "[...]/IncarnaMind/docs2db.py", line 123, in file_names2pickle
    with open(f"{embedding_store_path}/{name}.pkl", "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'database_store/file_names.pkl'
```

**Desktop:**
 - OS: MacOS 12.5.1
 - Python 3.10.13

**Comment by junruxiong** [comment]
Yeah, because you don't have database_store/ folder, Add:
if not os.path.exists(embedding_store_path):
        os.makedirs(embedding_store_path)
Before 
with open(f"{embedding_store_path}/{name}.pkl", "wb") as file:
        pickle.dump(file_names, file)
        
 Or, you can **sync the latest main branch**, thank you.
