### ISSUE TITLE
is there any limitation about the pdf file?

### ISSUE THREAD

**Issue by bigbrother666sh** [junruxiong/IncarnaMind#6]
**Describe the bug**
'cause when I use your sample files, things go well. 
Well when I try my own pdf files, it returns that:

File "...../IncarnaMind/docs2db.py", line 181, in process_metadata
 file_name_with_extension = os.path.basename(doc[0].metadata["source"])

indexError: list index out of range

any reply will be appreciated..

cheers

**Comment by junruxiong** [comment]
Hi, can you please run the below code to check if the document metadata exists?

```
for d in doc:
    print("metadata:", d.metadata)
```

before line 181: file_name = doc[0].metadata["source"].split("/")[-1].split(".")[0]


Some PDF files may be unable to get metadata, but I'm not entirely sure. If you can find files without metadata and kindly share them with me for testing, that would be great. Thank you.

**Comment by bigbrother666sh** [comment]
hi, after checking the pdf files again, I find the root cause:
one of my files is a purely ocr documents, that means there's only pics, no text...

from my understanding, it's totally another question now.... well, I still paste the terminal infomation here just for your interesting..

`(IncarnaMind) dsw@linfen-station:~/IncarnaMind$ python docs2db.py 
Processing files:   0%|                                   | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/dsw/IncarnaMind/docs2db.py", line 348, in <module>
    process_files()
  File "/home/dsw/IncarnaMind/docs2db.py", line 329, in process_files
    process_metadata(chunk_split_small)
  File "/home/dsw/IncarnaMind/docs2db.py", line 183, in process_metadata
    file_name_with_extension = os.path.basename(doc[0].metadata["source"])

IndexError: list index out of range
`

and you can find the pdf file here [aaa.pdf](https://github.com/junruxiong/IncarnaMind/files/12773339/aaa.pdf)

thanks again for your amazing work and quick reply
