### ISSUE TITLE
"uvloop does not support Windows at the moment"

### ISSUE THREAD

**Issue by tra38** [junruxiong/IncarnaMind#7]
**Describe the bug**
When I attempt to install the requirements of IncaraMind, I get this error:

Collecting uvloop==0.17.0 (from -r requirements.txt (line 93))
  Using cached uvloop-0.17.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\<user>\AppData\Local\Temp\pip-install-ptk0tavy\uvloop_0f7fadd821614c74944b94a8d189d891\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**To Reproduce**
1. Follow instructions on README on a Windows machine. You should see this error when you run "pip install -r requirements.txt".

**Expected behavior**
I am able to install all packages on Windows, without encountering any potential issue with the application.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home, 22H2
 - Version 22H2

**Comment by bigbrother666sh** [comment]
do. 
pip cache purge 
first

**Comment by tra38** [comment]
Tried that, and it didn't work.

```
Collecting uvloop==0.17.0 (from -r requirements.txt (line 93))
  Downloading uvloop-0.17.0.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tariq\AppData\Local\Temp\pip-install-5v7xfksy\uvloop_c5a01b02946f4d25b185d15bd7861e27\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

For now, I'm removing ```uvloop``` from requirements.txt, hoping that it won't lead to any issues in the future.

**Comment by junruxiong** [comment]
Hi @tra38. I've cleaned up the packages in requirement.txt. You can pull the main branch to update package requirements. The only necessary packages are below for now: 

chromadb==0.4.13
InstructorEmbedding==1.0.1
langchain==0.0.305
openai==0.28.1
pypdf==3.16.2
rank-bm25==0.2.2
sentence-transformers==2.2.2
tiktoken==0.5.1
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
together==0.2.4
tqdm==4.66.1
